version: "3.9"

services:
  pki-service:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: pki-2fa-dev
    ports:
      - "8080:8080"

    volumes:
      - ./student_private.pem:/app/student_private.pem:ro
      - ./student_public.pem:/app/student_public.pem:ro
      - ./instructor_public.pem:/app/instructor_public.pem:ro
      - seed-data:/data
      - cron-output:/cron

    environment:
      - TZ=UTC

    restart: unless-stopped

volumes:
  seed-data:
  cron-output:
